import sys
import pythoncom
import subprocess
from tkinter import Tk
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from win32com.client import Dispatch, gencache
from tkinter.filedialog import askopenfilenames
from compas_api import parse_design_documents, print_to_excel


table = None

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(747, 472)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 591))
        self.tabWidget.setStyleSheet("background-color: rgb(180, 199, 200);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(60, 110, 641, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(60, 200, 671, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(60, 80, 641, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(60, 170, 671, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(30, 40, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(60, 140, 671, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 221, 141))
        self.groupBox.setStyleSheet("font: 75 15pt \"MS Shell Dlg 2\";")
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(30, 30, 111, 17))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.radioButton.setFont(font)
        self.radioButton.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(30, 70, 131, 17))
        self.radioButton_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setGeometry(QtCore.QRect(30, 110, 131, 17))
        self.radioButton_3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.radioButton_3.setObjectName("radioButton_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 180, 221, 141))
        self.groupBox_2.setStyleSheet("font: 75 15pt \"MS Shell Dlg 2\";")
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_4.setGeometry(QtCore.QRect(30, 30, 141, 17))
        self.radioButton_4.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_5.setGeometry(QtCore.QRect(30, 70, 131, 17))
        self.radioButton_5.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_6.setGeometry(QtCore.QRect(30, 110, 141, 17))
        self.radioButton_6.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.radioButton_6.setObjectName("radioButton_6")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(280, 20, 441, 301))
        self.groupBox_3.setStyleSheet("font: 75 15pt \"MS Shell Dlg 2\";")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(20, 50, 81, 21))
        self.label.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_name = QtWidgets.QLabel(self.groupBox_3)
        self.label_name.setGeometry(QtCore.QRect(120, 50, 81, 21))
        self.label_name.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_name.setObjectName("label_2")
        self.label_format = QtWidgets.QLabel(self.groupBox_3)
        self.label_format.setGeometry(QtCore.QRect(370, 50, 61, 21))
        self.label_format.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_format.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(240, 50, 111, 21))
        self.label_4.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.label_des = QtWidgets.QLabel(self.groupBox_3)
        self.label_des.setGeometry(QtCore.QRect(120, 100, 81, 21))
        self.label_des.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_des.setObjectName("label_5")
        self.label_scale = QtWidgets.QLabel(self.groupBox_3)
        self.label_scale.setGeometry(QtCore.QRect(370, 100, 81, 21))
        self.label_scale.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_scale.setObjectName("label_6")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(240, 100, 111, 21))
        self.label_13.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(20, 100, 91, 21))
        self.label_14.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_14.setObjectName("label_14")
        self.label_tt = QtWidgets.QLabel(self.groupBox_3)
        self.label_tt.setGeometry(QtCore.QRect(120, 150, 81, 21))
        self.label_tt.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_tt.setObjectName("label_15")
        self.label_nt = QtWidgets.QLabel(self.groupBox_3)
        self.label_nt.setGeometry(QtCore.QRect(260, 250, 61, 21))
        self.label_nt.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_nt.setObjectName("label_16")
        self.label_dimension = QtWidgets.QLabel(self.groupBox_3)
        self.label_dimension.setGeometry(QtCore.QRect(260, 200, 81, 21))
        self.label_dimension.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_dimension.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(20, 150, 81, 21))
        self.label_18.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_18.setObjectName("label_18")
        self.label_lit = QtWidgets.QLabel(self.groupBox_3)
        self.label_lit.setGeometry(QtCore.QRect(370, 150, 61, 21))
        self.label_lit.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_lit.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setGeometry(QtCore.QRect(90, 250, 131, 21))
        self.label_20.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        self.label_21.setGeometry(QtCore.QRect(240, 150, 111, 21))
        self.label_21.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setGeometry(QtCore.QRect(90, 200, 131, 21))
        self.label_22.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_22.setObjectName("label_22")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(120, 360, 521, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(50)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_6 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.add_functions()
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Расчет нормы времени на создание чертежей"))
        self.label_7.setText(_translate("MainWindow",
                                        "2. Затем  выберите тип чертежа. Это также влияет на поправочные коэффициенты и алгоритм расчета"))
        self.label_8.setText(_translate("MainWindow",
                                        "5. После этого, если вам нужен файл с отчетом о проделанной работе нажмите кнопку 'Сохранить отчет'"))
        self.label_9.setText(_translate("MainWindow",
                                        "1. Для выберите тип производства. Это влияет на поправочные коэффициенты"))
        self.label_10.setText(_translate("MainWindow",
                                         "4. Программа расчитает норму времени вашего чертежа и заполнит поля, помеченные '***'"))
        self.label_11.setText(_translate("MainWindow", "Памятка при расчете"))
        self.label_12.setText(_translate("MainWindow",
                                         "3.Нажмите кнопку 'Выбрать чертеж для расчета' и с помощью проводника выберите нужный файл"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Памятка"))
        self.groupBox.setTitle(_translate("MainWindow", "Тип производства"))
        self.radioButton.setText(_translate("MainWindow", "Единичное"))
        self.radioButton_2.setText(_translate("MainWindow", "Серийное"))
        self.radioButton_3.setText(_translate("MainWindow", "Массовое"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Тип чертежа"))
        self.radioButton_4.setText(_translate("MainWindow", "Общего вида"))
        self.radioButton_5.setText(_translate("MainWindow", "Сборочный"))
        self.radioButton_6.setText(_translate("MainWindow", "Чертеж детали"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Результаты расчета"))
        self.label.setText(_translate("MainWindow", "Имя файла"))
        self.label_name.setText(_translate("MainWindow", "***"))
        self.label_format.setText(_translate("MainWindow", "***"))
        self.label_4.setText(_translate("MainWindow", "Формат листа"))
        self.label_des.setText(_translate("MainWindow", "***"))
        self.label_scale.setText(_translate("MainWindow", "***"))
        self.label_13.setText(_translate("MainWindow", "Масштаб"))
        self.label_14.setText(_translate("MainWindow", "Разработал"))
        self.label_tt.setText(_translate("MainWindow", "***"))
        self.label_nt.setText(_translate("MainWindow", "***"))
        self.label_dimension.setText(_translate("MainWindow", "***"))
        self.label_18.setText(_translate("MainWindow", "Пукнты ТТ"))
        self.label_lit.setText(_translate("MainWindow", "***"))
        self.label_20.setText(_translate("MainWindow", "Норма времени"))
        self.label_21.setText(_translate("MainWindow", "Литера"))
        self.label_22.setText(_translate("MainWindow", "Кол-во размеров"))
        self.pushButton_4.setText(_translate("MainWindow", "Выбрать чертеж для расчета"))
        self.pushButton_6.setText(_translate("MainWindow", "Сохранить результаты"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Расчет нормы времени"))

    def add_functions(self):
        # Метод расчета нормы времени
        self.pushButton_4.clicked.connect(lambda: self.calculation_norm_time())
        # Печать в excel
        self.pushButton_6.clicked.connect(lambda: self.print_excel())

    def calculation_norm_time(self):
        root = Tk()
        root.withdraw()  # Скрываем основное окно и сразу окно выбора файлов

        filenames = askopenfilenames(title="Выберете чертежи деталей",
                                     filetypes=[('Kompas 3D', '*.cdw'),])

        global table
        if not self.radioButton_5.isChecked():
            table = parse_design_documents(filenames, self)
        else:
            error = QMessageBox()
            error.setWindowTitle("Ошибка")
            error.setText("Для данного типа чертежа невозможно выполнить расчет!")
            error.setIcon(QMessageBox.Warning)
            error.setStandardButtons(QMessageBox.Ok|QMessageBox.Close)
            error.exec_()

        root.destroy()  # Уничтожаем основное окно
        root.mainloop()

    def print_excel(self):
        global table
        if table:

            print_to_excel(table, self)
        else:
            error = QMessageBox()
            error.setWindowTitle("Предупреждение")
            error.setText("Сейчас данное действие выполнить нельзя!")
            error.setIcon(QMessageBox.Warning)
            error.setStandardButtons(QMessageBox.Ok | QMessageBox.Close)
            error.exec_()


